/* eslint-disable no-undef -- WebRTC interfaces are browser-provided TypeScript globals. */
import type { AuthUser, CallType, ChatDto } from '@chat-app/shared';
import { useCallback, useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';

import { WebRtcPeer } from '@/features/calls/webrtc-peer';
import { getSocket } from '@/lib/socket';
import { SOCKET_EVENTS } from '@/lib/socket-events';

type CallPhase = 'idle' | 'preparing' | 'outgoing-ringing' | 'incoming-ringing' | 'accepting' | 'connecting' | 'connected' | 'rejected' | 'cancelled' | 'busy' | 'ended' | 'failed';
type CurrentCall = { id: string; chat: ChatDto; peer: AuthUser; type: CallType; direction: 'incoming' | 'outgoing'; phase: CallPhase };
const acknowledge = <T,>(socket: ReturnType<typeof getSocket>, event: string, payload: unknown) => new Promise<T>((resolve, reject) => socket.emit(event, payload, (reply: { ok: boolean; data?: T; error?: { message: string } }) => reply.ok ? resolve(reply.data as T) : reject(new Error(reply.error?.message ?? 'Call action failed'))));

export const useCallController = (token: string | null, user: AuthUser | null) => {
  const peerRef = useRef<WebRtcPeer | null>(null); const currentRef = useRef<CurrentCall | null>(null);
  const [call, setCall] = useState<CurrentCall | null>(null); const [localStream, setLocalStream] = useState<MediaStream | null>(null); const [remoteStream, setRemoteStream] = useState<MediaStream | null>(null); const [muted, setMuted] = useState(false); const [cameraOff, setCameraOff] = useState(false);
  const cleanup = useCallback(() => { peerRef.current?.cleanup(); peerRef.current = null; currentRef.current = null; setLocalStream(null); setRemoteStream(null); setMuted(false); setCameraOff(false); setCall(null); }, []);
  const startMedia = useCallback(async (type: CallType, socket: ReturnType<typeof getSocket>) => { const peer = new WebRtcPeer(); peerRef.current = peer; const stream = await peer.start(type, { onIceCandidate: (candidate) => { const id = currentRef.current?.id; if (id) socket.emit(SOCKET_EVENTS.CALL_ICE_CANDIDATE, { callId: id, candidate }); }, onRemoteStream: setRemoteStream, onConnectionState: (state) => { if (state === 'connected') setCall((c) => c ? { ...c, phase: 'connected' } : c); if (state === 'failed' || state === 'closed') cleanup(); } }); setLocalStream(stream); return peer; }, [cleanup]);
  const begin = useCallback(async (chat: ChatDto, type: CallType) => { if (!token || !user || chat.isGroupChat || currentRef.current) return; const peer = chat.participants.find((p) => p.id !== user.id); if (!peer) return; const socket = getSocket(token); try { setCall({ id: '', chat, peer, type, direction: 'outgoing', phase: 'preparing' }); await startMedia(type, socket); const data = await acknowledge<{ callId: string }>(socket, SOCKET_EVENTS.CALL_INITIATE, { chatId: chat.id, type }); const next = { id: data.callId, chat, peer, type, direction: 'outgoing' as const, phase: 'outgoing-ringing' as const }; currentRef.current = next; setCall(next); } catch (error) { cleanup(); toast.error(error instanceof Error ? error.message : 'Unable to start call'); } }, [cleanup, startMedia, token, user]);
  const end = useCallback(async (event: string = SOCKET_EVENTS.CALL_END) => { const current = currentRef.current; if (token && current?.id) { try { await acknowledge(getSocket(token), event, { callId: current.id }); } catch { /* terminal cleanup remains local */ } } cleanup(); }, [cleanup, token]);
  const accept = useCallback(async () => { const current = currentRef.current; if (!token || !current || current.direction !== 'incoming') return; try { setCall((c) => c ? { ...c, phase: 'accepting' } : c); const socket = getSocket(token); await startMedia(current.type, socket); await acknowledge(socket, SOCKET_EVENTS.CALL_ACCEPT, { callId: current.id }); setCall((c) => c ? { ...c, phase: 'connecting' } : c); } catch (error) { await end(SOCKET_EVENTS.CALL_REJECT); toast.error(error instanceof Error ? error.message : 'Microphone permission was not granted'); } }, [end, startMedia, token]);
  useEffect(() => { if (!token || !user) return; const socket = getSocket(token); if (!socket.connected) socket.connect(); const incoming = (data: { callId: string; chatId: string; callerId: string; type: CallType }) => { if (currentRef.current) return; const chat = { id: data.chatId } as ChatDto; const peer = { id: data.callerId, name: 'Incoming caller', username: '', email: '', avatarUrl: null } as AuthUser; const next = { id: data.callId, chat, peer, type: data.type, direction: 'incoming' as const, phase: 'incoming-ringing' as const }; currentRef.current = next; setCall(next); };
    const accepted = async ({ callId }: { callId: string }) => { if (currentRef.current?.id !== callId || currentRef.current.direction !== 'outgoing') return; const offer = await peerRef.current?.createOffer(); if (offer) socket.emit(SOCKET_EVENTS.CALL_OFFER, { callId, description: offer }); setCall((c) => c ? { ...c, phase: 'connecting' } : c); };
    const offer = async ({ callId, description }: { callId: string; description: RTCSessionDescriptionInit }) => { if (currentRef.current?.id !== callId) return; await peerRef.current?.setRemoteDescription(description); const answer = await peerRef.current?.createAnswer(); if (answer) socket.emit(SOCKET_EVENTS.CALL_ANSWER, { callId, description: answer }); };
    const answer = async ({ callId, description }: { callId: string; description: RTCSessionDescriptionInit }) => { if (currentRef.current?.id === callId) await peerRef.current?.setRemoteDescription(description); };
    const ice = ({ callId, candidate }: { callId: string; candidate: RTCIceCandidateInit }) => { if (currentRef.current?.id === callId) void peerRef.current?.addIceCandidate(candidate); };
    const terminal = ({ callId }: { callId: string }) => { if (currentRef.current?.id === callId) cleanup(); };
    socket.on(SOCKET_EVENTS.CALL_INCOMING, incoming).on(SOCKET_EVENTS.CALL_ACCEPTED, accepted).on(SOCKET_EVENTS.CALL_OFFER, offer).on(SOCKET_EVENTS.CALL_ANSWER, answer).on(SOCKET_EVENTS.CALL_ICE_CANDIDATE, ice).on(SOCKET_EVENTS.CALL_ENDED, terminal);
    return () => { socket.off(SOCKET_EVENTS.CALL_INCOMING, incoming).off(SOCKET_EVENTS.CALL_ACCEPTED, accepted).off(SOCKET_EVENTS.CALL_OFFER, offer).off(SOCKET_EVENTS.CALL_ANSWER, answer).off(SOCKET_EVENTS.CALL_ICE_CANDIDATE, ice).off(SOCKET_EVENTS.CALL_ENDED, terminal); cleanup(); };
  }, [cleanup, token, user]);
  return { call, localStream, remoteStream, muted, cameraOff, begin, accept, end, setMuted: (value: boolean) => { peerRef.current?.setMuted(value); setMuted(value); }, setCameraOff: (value: boolean) => { peerRef.current?.setCameraOff(value); setCameraOff(value); } };
};
